### ISSUE TITLE
Parallel Gateways & Workflows

### ISSUE THREAD

**Issue by MrBugMiner** [phpmentors-jp/workflower#13]
Hi.

Can I use workflower for parallel workflows ?
I don't see parallel gateway in your project.
How about "diverging" and "converging" parallel gateways ?

How about another types of gateways ?

Please tell me how to implement parallel gateways and workflows with workflower ?

Thanks.
Jalaal

**Comment by mattsches** [comment]
Any further thoughts on how to implement Parallel Gateways? One of the issues at hand is that we cannot have two parallel states in the state machine. IMHO this prevents splitting up a workflow in two parallel flows (which is basically what a state machine is made for, so I'm probably fine with this).

I'm currently thinking of encapsulating parallel flows in a subprocess (aka `ParallelTask`) that contains one or multiple sub-workflows and can only be completed once those sub-workflows are ended. This might work for our use case, but possibly restricts other use cases.

I'm open for other suggestions, though ;)

**Comment by SirWaddles** [comment]
I personally think it might be worth refactoring out Stagehand's FSM, this is a pretty clear cut case of where it's adding complexity where it's meant to be simplifiying it, I don't think a BPMN workflow can really be adequately represented as a fininte state automaton.

The only thing I can think of that would have this work without requiring multiple FSMs in the Workflow state is to create a cartesian product of the parallel tasks, but the memory trade-off seems ridiculous.

**Comment by alxh77** [comment]
I think instead of the FSM you need something like a petri net. Maybe https://github.com/florianv/petrinet/ is the right software for this task.

**Comment by iteman** [comment]
Fork and Join have been supported by Stagehand_FSM.

https://github.com/phpmentors-jp/stagehand-fsm/pull/32

**Comment by iteman** [comment]
Parallel Gateway is now supported in the `master` branch. As a result, I introduced tokens and stopped using the FSM.
Thanks!
