### ISSUE TITLE
Initial usage

### ISSUE THREAD

**Issue by falinhares** [phpmentors-jp/workflower#19]
Hello,

I've checked the other posts and they did not cover my issue.

I've installed workflower on my PHP project through Composer using this composer.json:

{
    "require": {
        "phpmentors/workflower": "1.2.*",
		"phpmentors/workflower-bundle": "1.0.*"
    }
}

I'd like to know what is the next step to start using this project in order to see a window with a workflow since there is no manual in english.

Thanks

**Comment by iteman** [comment]
The Quick Start Guide https://github.com/phpmentors-jp/workflower/blob/master/docs/GUIDE.md has just been added! :smile:
