### ISSUE TITLE
The service "phpmentors_workflower.security_participant" has a dependency on a non-existent service "security.access.role_hierarchy_voter".

### ISSUE THREAD

**Issue by Slavenin** [phpmentors-jp/workflower#36]
Hi!
I install symfony
 -------------------- -------------------------------------------
  Symfony
 -------------------- -------------------------------------------
  Version              3.3.6
  End of maintenance   01/2018
  End of life          07/2018
 -------------------- -------------------------------------------
  Kernel
 -------------------- -------------------------------------------
  Type                 AppKernel
  Name                 app
  Environment          dev
  Debug                true
  Charset              UTF-8
  Root directory       ./app
  Cache directory      ./var/cache/dev (1.5 MiB)
  Log directory        ./var/logs (1 KiB)
 -------------------- -------------------------------------------
  PHP
 -------------------- -------------------------------------------
  Version              7.0.20
  Architecture         64 bits
  Intl locale          n/a
  Timezone             Europe/Moscow (2017-08-23T15:26:39+03:00)
  OPcache              true
  APCu                 true
  Xdebug               true
 -------------------- -------------------------------------------

and install bundle how in docs. But when i open site i see:
![image](https://user-images.githubusercontent.com/4180077/29615729-b187ae1c-8817-11e7-85c9-9ad9ffb6d318.png)

**Comment by iteman** [comment]
WorkflowerBundle 1.4.0 could be used without  `security.access.role_hierarchy_voter`.
