### ISSUE TITLE
Serializing Error in ExclusiveGateway Class.

### ISSUE THREAD

**Issue by rockancun** [phpmentors-jp/workflower#55]
At line 61 serialize ExclusiveGateway class the attibute defaultSequenceFlow is renamed for defaultSequenceFlowId.

When unserialize the object lost the value of attribute defaultSequenceFlow

`public function serialize()
    {
        return serialize(array(
            'id' => $this->id,
            'name' => $this->name,
            'role' => $this->role,
            'defaultSequenceFlow' => $this->defaultSequenceFlowId,
        ));
    }`

**Comment by iteman** [comment]
@rockancun I got it! Thank you!
