### ISSUE TITLE
Parallel sequence flows

### ISSUE THREAD

**Issue by ateodorescu** [phpmentors-jp/workflower#72]
A sequence flow can have a condition defined on it. When a BPMN 2.0 activity is left, the default behaviour is to evaluate the conditions on the outgoing sequence flows. When a condition evaluates ‘true’, that outgoing sequence flow is selected. When multiple sequence flows are selected that way, multiple executions will be generated and the process is continued in a parallel way.

**Comment by ateodorescu** [comment]
Fixed in https://github.com/phpmentors-jp/workflower/pull/73

**Comment by iteman** [comment]
I hadn't considered that. I will merge #73. Thank you! 😄
