### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by freeyland** [phpmentors-jp/workflower#9]
Dear,
Would you have some kind of documentation or example how to youse your code.

Thanx,
Frederick

**Comment by iteman** [comment]
I wrote a quick start guide to manage business processes with Workflower on Symfony application.

http://phpmentors.jp/post/135905985688/practical-symfony-28-bpm-with-workflower

It's written in Japanese, but it includes code that would help you.

**Comment by bretrzaun** [comment]
I agree - some documentation (in english) would make this very interesting project understandable by a wider audience.
Workflow components are rare in the PHP world, which makes this one even more interesting.

**Comment by freeyland** [comment]
Very difficult to read the examples with Japanese text. How hard would it be for you to translate?

**Comment by iteman** [comment]
A quick start guide in English will be available sometime soon.
It's not very difficult for me, but I'm quite busy and there is quality problem :sweat_smile:

**Comment by cymapgt** [comment]
Hi, Once populating the workflow with the participants is it up to the implementer to control the execution e.g. a $workflow->execute() method?

**Comment by iteman** [comment]
In Workflower, a `Role` is mapped to a `Swimlane` of the workflow at source time to define the owner of the workflow elements on the lane, while a `Participant` is mapped to `WorkItems` at runtime to define the person (or not person) who will execute the `Activity`. And a `Workflow` object will check whether or not the given participant (usually the current user) has the role of the current activity on `allocateWorkItem()`, `startWorkItem()`, and `completeWorkItem()`.

**Comment by iteman** [comment]
@cymapgt Congratulations!

If you use [PHPMentorsWorkflowerBundle](https://github.com/phpmentors-jp/workflower-bundle), you can inject a [WorkItemContext](https://github.com/phpmentors-jp/workflower/blob/v1.0.0/src/Process/WorkItemContext.php) object by using [phpmentors_workflower.work_item_context](https://github.com/phpmentors-jp/workflower-bundle/blob/v1.0.0/src/Resources/config/services.xml#L33) service to use a `WorkItemContext` object with the [SecurityParticipant](https://github.com/phpmentors-jp/workflower-bundle/blob/v1.0.0/src/Workflow/Participant/SecurityParticipant.php) object.

**Comment by iteman** [comment]
The Quick Start Guide https://github.com/phpmentors-jp/workflower/blob/master/docs/GUIDE.md has just been added! :smile:
